import { useMemo, useState, type ChangeEvent } from 'react';
import { AlertTriangleIcon, CheckCircle2Icon, ImageIcon, LinkIcon, LoaderCircleIcon, TextIcon, UploadCloudIcon } from 'lucide-react';
import Tesseract from 'tesseract.js';
import { toast } from 'react-hot-toast';
import SoftBackdrop from '../components/SoftBackdrop';
import { PrimaryButton } from '../components/Buttons';
import { useTheme } from '../context/theme';

type InputMode = 'text' | 'url' | 'image';
type Verdict = 'FAKE' | 'REAL' | 'UNCERTAIN';

interface PredictionResult {
    verdict: Verdict;
    confidence: number | null;
    explanation: string;
}

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8001';

function normalizePrediction(data: unknown): PredictionResult {
    const obj = (typeof data === 'object' && data !== null ? data : {}) as Record<string, unknown>;

    const rawVerdict = String(
        obj.label ?? obj.prediction ?? obj.class ?? obj.verdict ?? obj.result ?? 'uncertain'
    ).toLowerCase();

    let verdict: Verdict = 'UNCERTAIN';
    if (rawVerdict.includes('fake') || rawVerdict.includes('false')) {
        verdict = 'FAKE';
    } else if (rawVerdict.includes('real') || rawVerdict.includes('true') || rawVerdict.includes('legit')) {
        verdict = 'REAL';
    }

    const confidenceCandidate =
        obj.confidence ?? obj.score ?? obj.probability ?? obj.confidence_score ?? null;

    const numericConfidence =
        typeof confidenceCandidate === 'number'
            ? confidenceCandidate <= 1
                ? confidenceCandidate * 100
                : confidenceCandidate
            : null;

    const explanation = String(
        obj.explanation ?? obj.reason ?? obj.summary ?? 'Prediction generated by the API.'
    );

    return {
        verdict,
        confidence: numericConfidence,
        explanation,
    };
}

export default function Analyze() {
    const { isDark } = useTheme();
    const [mode, setMode] = useState<InputMode>('text');
    const [textInput, setTextInput] = useState('');
    const [urlInput, setUrlInput] = useState('');
    const [imageFile, setImageFile] = useState<File | null>(null);
    const [ocrText, setOcrText] = useState('');
    const [result, setResult] = useState<PredictionResult | null>(null);
    const [loading, setLoading] = useState(false);

    const confidenceLabel = useMemo(() => {
        if (result?.confidence == null) {
            return 'N/A';
        }
        return `${result.confidence.toFixed(1)}%`;
    }, [result]);

    const verdictStyle = useMemo(() => {
        if (!result) {
            return {
                icon: isDark ? 'text-gray-300' : 'text-slate-600',
                badge: isDark
                    ? 'text-gray-100 border-white/30 bg-white/10'
                    : 'text-slate-700 border-slate-300 bg-slate-100',
            };
        }

        if (result.verdict === 'FAKE') {
            return {
                icon: isDark ? 'text-amber-300' : 'text-amber-700',
                badge: isDark
                    ? 'text-amber-100 border-amber-300/50 bg-amber-700/25'
                    : 'text-amber-900 border-amber-300 bg-amber-100',
            };
        }

        if (result.verdict === 'REAL') {
            return {
                icon: isDark ? 'text-emerald-300' : 'text-emerald-700',
                badge: isDark
                    ? 'text-emerald-100 border-emerald-300/50 bg-emerald-700/25'
                    : 'text-emerald-900 border-emerald-300 bg-emerald-100',
            };
        }

        return {
            icon: isDark ? 'text-gray-200' : 'text-slate-700',
            badge: isDark
                ? 'text-gray-100 border-white/30 bg-white/10'
                : 'text-slate-700 border-slate-300 bg-slate-100',
        };
    }, [isDark, result]);

    const runTextAnalysis = async (text: string) => {
        const response = await fetch(`${API_BASE_URL}/predict`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ text }),
        });

        const payload = await response.json();
        if (!response.ok) {
            throw new Error(String((payload as { detail?: string }).detail ?? 'Failed to analyze text.'));
        }

        return normalizePrediction(payload);
    };

    const handleAnalyze = async () => {
        try {
            setLoading(true);
            setResult(null);

            if (mode === 'text') {
                const cleanText = textInput.trim();
                if (cleanText.length < 5) {
                    toast.error('Please enter at least a short claim or headline.');
                    return;
                }
                const analyzed = await runTextAnalysis(cleanText);
                setResult(analyzed);
                toast.success(`Analysis complete: ${analyzed.verdict}`);
                return;
            }

            if (mode === 'url') {
                const cleanUrl = urlInput.trim();
                if (!cleanUrl) {
                    toast.error('Please enter a website URL.');
                    return;
                }

                const response = await fetch(`${API_BASE_URL}/analyze-url`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ url: cleanUrl }),
                });

                const payload = await response.json();
                if (!response.ok) {
                    throw new Error(String((payload as { detail?: string }).detail ?? 'Failed to analyze URL.'));
                }

                const analyzed = normalizePrediction(payload);
                setResult(analyzed);
                toast.success(`Analysis complete: ${analyzed.verdict}`);
                return;
            }

            if (!imageFile) {
                toast.error('Please select an image first.');
                return;
            }

            const ocr = await Tesseract.recognize(imageFile, 'eng');
            const extracted = ocr.data.text.trim();
            setOcrText(extracted);

            if (extracted.length < 10) {
                toast.error('Could not read enough text from the image. Try a clearer image.');
                return;
            }

            const analyzed = await runTextAnalysis(extracted);
            setResult(analyzed);
            toast.success(`Analysis complete: ${analyzed.verdict}`);
        } catch (error) {
            const message = error instanceof Error ? error.message : 'Could not complete analysis.';
            toast.error(message);
        } finally {
            setLoading(false);
        }
    };

    const onImageChange = (event: ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0] ?? null;
        setImageFile(file);
        setOcrText('');
    };

    return (
        <main className={`min-h-screen relative overflow-hidden px-4 pt-28 pb-14 md:pt-32 md:pb-16 ${isDark ? 'bg-gray-950 text-white' : 'bg-slate-50 text-slate-900'}`}>
            <SoftBackdrop />
            <div className='relative z-10 max-w-6xl mx-auto'>
                <section className={`rounded-3xl border backdrop-blur-md p-6 md:p-8 ${
                    isDark
                        ? 'border-cyan-500/20 bg-linear-to-b from-cyan-900/20 via-slate-950/70 to-slate-950/85'
                        : 'border-cyan-300/50 bg-linear-to-b from-cyan-100/80 via-white/80 to-slate-100/90 shadow-2xl shadow-cyan-900/10'
                }`}>
                    <div className='mb-7'>
                        <h1 className='text-3xl md:text-4xl font-semibold'>Free News Fact Analysis</h1>
                        <p className={`text-sm md:text-base mt-2 ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>
                            Check a claim by text, website link, or image containing text.
                        </p>
                    </div>

                    <div className='flex flex-wrap gap-2 mb-6'>
                        <button
                            onClick={() => setMode('text')}
                            className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm border transition ${
                                mode === 'text'
                                    ? 'border-cyan-400 text-cyan-300 bg-cyan-600/10'
                                    : isDark
                                        ? 'border-white/10 text-gray-300 hover:bg-white/5'
                                        : 'border-slate-300 text-slate-600 hover:bg-slate-100'
                            }`}
                        >
                            <TextIcon className='size-4' /> Text
                        </button>

                        <button
                            onClick={() => setMode('url')}
                            className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm border transition ${
                                mode === 'url'
                                    ? 'border-cyan-400 text-cyan-300 bg-cyan-600/10'
                                    : isDark
                                        ? 'border-white/10 text-gray-300 hover:bg-white/5'
                                        : 'border-slate-300 text-slate-600 hover:bg-slate-100'
                            }`}
                        >
                            <LinkIcon className='size-4' /> Website Link
                        </button>

                        <button
                            onClick={() => setMode('image')}
                            className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm border transition ${
                                mode === 'image'
                                    ? 'border-cyan-400 text-cyan-300 bg-cyan-600/10'
                                    : isDark
                                        ? 'border-white/10 text-gray-300 hover:bg-white/5'
                                        : 'border-slate-300 text-slate-600 hover:bg-slate-100'
                            }`}
                        >
                            <ImageIcon className='size-4' /> Image
                        </button>
                    </div>

                    <div className='grid lg:grid-cols-2 gap-5'>
                        <div className={`rounded-2xl border p-5 ${isDark ? 'border-white/10 bg-black/30' : 'border-slate-200 bg-white/80'}`}>
                            {mode === 'text' && (
                                <>
                                    <label className={`text-sm font-medium ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>News Text</label>
                                    <textarea
                                        value={textInput}
                                        onChange={(e) => setTextInput(e.target.value)}
                                        placeholder='Paste headline or article text'
                                        className={`mt-2 w-full min-h-52 rounded-xl border px-4 py-3 text-sm outline-none focus:border-cyan-400/50 ${
                                            isDark
                                                ? 'border-white/10 bg-black/30 text-white placeholder:text-gray-400'
                                                : 'border-slate-300 bg-white text-slate-800 placeholder:text-slate-400'
                                        }`}
                                    />
                                </>
                            )}

                            {mode === 'url' && (
                                <>
                                    <label className={`text-sm font-medium ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>Website URL</label>
                                    <input
                                        value={urlInput}
                                        onChange={(e) => setUrlInput(e.target.value)}
                                        placeholder='https://example.com/news-article'
                                        className={`mt-2 w-full rounded-xl border px-4 py-3 text-sm outline-none focus:border-cyan-400/50 ${
                                            isDark
                                                ? 'border-white/10 bg-black/30 text-white placeholder:text-gray-400'
                                                : 'border-slate-300 bg-white text-slate-800 placeholder:text-slate-400'
                                        }`}
                                    />
                                    <p className={`text-xs mt-2 ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>
                                        We fetch readable page text and run analysis on it.
                                    </p>
                                </>
                            )}

                            {mode === 'image' && (
                                <>
                                    <label className={`text-sm font-medium ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>Upload Image</label>
                                    <label className={`mt-2 flex flex-col items-center justify-center rounded-xl border border-dashed px-4 py-8 text-center cursor-pointer transition ${
                                        isDark ? 'border-white/20 bg-black/20 hover:bg-black/30' : 'border-slate-300 bg-slate-50 hover:bg-slate-100'
                                    }`}>
                                        <UploadCloudIcon className='size-7 mb-2 text-cyan-400' />
                                        <span className='text-sm'>Click to select image</span>
                                        <span className={`text-xs mt-1 ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>
                                            OCR will extract text before analysis
                                        </span>
                                        <input type='file' accept='image/*' className='hidden' onChange={onImageChange} />
                                    </label>

                                    {imageFile && (
                                        <p className={`text-xs mt-2 ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>
                                            Selected: {imageFile.name}
                                        </p>
                                    )}

                                    {!!ocrText && (
                                        <div className={`mt-3 rounded-xl border p-3 text-xs leading-relaxed ${isDark ? 'border-white/10 bg-black/30 text-gray-300' : 'border-slate-300 bg-white text-slate-600'}`}>
                                            OCR preview: {ocrText.slice(0, 280)}{ocrText.length > 280 ? '...' : ''}
                                        </div>
                                    )}
                                </>
                            )}

                            <div className='mt-4'>
                                <PrimaryButton onClick={handleAnalyze} disabled={loading} className='px-6 py-3 disabled:opacity-60'>
                                    {loading ? <LoaderCircleIcon className='size-4 animate-spin' /> : <CheckCircle2Icon className='size-4' />}
                                    {loading ? 'Analyzing...' : 'Check Fact'}
                                </PrimaryButton>
                            </div>
                        </div>

                        <div className={`rounded-2xl border p-5 ${isDark ? 'border-white/10 bg-black/30' : 'border-slate-200 bg-white/80'}`}>
                            <p className={`text-sm font-medium ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>Result</p>

                            {!result && (
                                <div className={`mt-3 rounded-xl border border-dashed p-4 text-sm ${
                                    isDark
                                        ? 'border-white/15 bg-black/20 text-gray-300'
                                        : 'border-slate-300 bg-slate-50 text-slate-600'
                                }`}>
                                    Run analysis to see verdict, confidence and explanation.
                                </div>
                            )}

                            {result && (
                                <div className='mt-4 space-y-4'>
                                    <div className={`flex items-center justify-between rounded-xl border p-4 ${isDark ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
                                        <div className='flex items-center gap-2'>
                                            {result.verdict === 'FAKE'
                                                ? <AlertTriangleIcon className={`size-5 ${verdictStyle.icon}`} />
                                                : <CheckCircle2Icon className={`size-5 ${verdictStyle.icon}`} />}
                                            <p className={`text-sm ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>Verdict</p>
                                        </div>
                                        <span className={`text-xs px-3 py-1 rounded-full border font-semibold tracking-wide ${verdictStyle.badge}`}>
                                            {result.verdict}
                                        </span>
                                    </div>

                                    <div className={`rounded-xl border p-4 ${isDark ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
                                        <p className={`text-sm ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>Confidence</p>
                                        <p className={`mt-1 text-2xl font-semibold ${isDark ? 'text-white' : 'text-slate-900'}`}>{confidenceLabel}</p>
                                    </div>

                                    <div className={`rounded-xl border p-4 ${isDark ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
                                        <p className={`text-sm ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>Explanation</p>
                                        <p className={`mt-2 text-sm leading-relaxed ${isDark ? 'text-gray-200' : 'text-slate-700'}`}>{result.explanation}</p>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                </section>
            </div>
        </main>
    );
}
