import { useMemo, useState } from 'react';
import { AlertTriangleIcon, CheckCircle2Icon, LoaderCircleIcon, RadarIcon } from 'lucide-react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import Title from './Title';
import { PrimaryButton, GhostButton } from './Buttons';
import { toast } from 'react-hot-toast';
import { useTheme } from '../context/theme';
import { getValidSession } from '../utils/session';

type Verdict = 'FAKE' | 'REAL' | 'UNCERTAIN';

interface NormalizedPrediction {
    verdict: Verdict;
    confidence: number | null;
    explanation: string;
}

const API_ENDPOINT = import.meta.env.VITE_ML_API_ENDPOINT ?? 'http://127.0.0.1:8001/predict';
const GUEST_DEMO_LIMIT = 3;
const GUEST_DEMO_COUNT_KEY = 'verilens_demo_guest_uses';

function normalizePrediction(data: unknown): NormalizedPrediction {
    const obj = (typeof data === 'object' && data !== null ? data : {}) as Record<string, unknown>;
    const nested = (typeof obj.result === 'object' && obj.result !== null ? obj.result : obj) as Record<string, unknown>;

    const rawVerdict = String(
        nested.label ?? nested.prediction ?? nested.class ?? nested.verdict ?? nested.result ?? 'uncertain'
    ).toLowerCase();

    let verdict: Verdict = 'UNCERTAIN';
    if (rawVerdict.includes('fake') || rawVerdict.includes('false')) {
        verdict = 'FAKE';
    } else if (rawVerdict.includes('real') || rawVerdict.includes('true') || rawVerdict.includes('legit')) {
        verdict = 'REAL';
    }

    const confidenceCandidate =
        nested.confidence ?? nested.score ?? nested.probability ?? nested.confidence_score ?? null;

    const numericConfidence =
        typeof confidenceCandidate === 'number'
            ? confidenceCandidate <= 1
                ? confidenceCandidate * 100
                : confidenceCandidate
            : null;

    const explanation = String(
        nested.explanation ?? nested.reason ?? nested.summary ?? 'Prediction generated by the ML endpoint.'
    );

    return {
        verdict,
        confidence: numericConfidence,
        explanation,
    };
}

export default function Demo() {
    const { isDark } = useTheme();
    const navigate = useNavigate();
    const [text, setText] = useState('Breaking: Scientists confirm moonlight cures all diseases overnight.');
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<NormalizedPrediction | null>(null);

    const confidenceLabel = useMemo(() => {
        if (result?.confidence == null) {
            return 'N/A';
        }

        return `${result.confidence.toFixed(1)}%`;
    }, [result]);

    const runPrediction = async () => {
        if (!text.trim()) {
            const message = 'Please enter a headline or article text first.';
            toast.error(message);
            return;
        }

        const token = localStorage.getItem('verilens_token');
        const session = getValidSession<{ id?: string }>();
        const hasUser = !!session?.user;

        const isLoggedIn = !!token && hasUser;

        if (!isLoggedIn) {
            const currentCount = Number(localStorage.getItem(GUEST_DEMO_COUNT_KEY) ?? '0');
            if (currentCount >= GUEST_DEMO_LIMIT) {
                toast.error('Demo limit reached. Please log in to continue.', { id: 'demo-login-required' });
                navigate('/login');
                return;
            }
        }

        setLoading(true);

        try {
            const response = await fetch(API_ENDPOINT, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ text: text.trim() }),
            });

            if (!response.ok) {
                throw new Error(`Request failed (${response.status}).`);
            }

            const payload: unknown = await response.json();
            const normalized = normalizePrediction(payload);
            setResult(normalized);

            if (!isLoggedIn) {
                const currentCount = Number(localStorage.getItem(GUEST_DEMO_COUNT_KEY) ?? '0');
                localStorage.setItem(GUEST_DEMO_COUNT_KEY, String(currentCount + 1));
            }

            toast.success(`Analysis complete: ${normalized.verdict}`);
        } catch {
            const message = `Could not reach API at ${API_ENDPOINT}. Check your backend URL and CORS settings.`;
            setResult(null);
            toast.error(message);
        } finally {
            setLoading(false);
        }
    };

    return (
        <section id="demo" className={`py-20 border-y ${isDark ? 'border-white/6 bg-white/2' : 'border-slate-200 bg-white/55'}`}>
            <div className="max-w-6xl mx-auto px-4">
                <Title
                    title="Try Demo"
                    heading="Run a live fake-news check"
                    description="Paste a headline or short article text. We send it to your ML API and show a prediction preview instantly."
                />

                <div className="grid lg:grid-cols-2 gap-6">
                    <motion.div
                        initial={{ y: 80, opacity: 0 }}
                        whileInView={{ y: 0, opacity: 1 }}
                        viewport={{ once: true }}
                        transition={{ type: 'spring', stiffness: 250, damping: 70, mass: 1 }}
                        className={`rounded-2xl border p-6 ${
                            isDark ? 'border-white/10 bg-slate-900/60' : 'border-slate-200 bg-white/90 shadow-xl shadow-slate-900/5'
                        }`}
                    >
                        <label htmlFor="demo-text" className={`text-sm font-medium ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>
                            News text input
                        </label>
                        <textarea
                            id="demo-text"
                            value={text}
                            onChange={(event) => setText(event.target.value)}
                            placeholder="Paste headline or article text..."
                            className={`mt-3 w-full min-h-44 rounded-xl border px-4 py-3 text-sm outline-none focus:border-cyan-400/50 ${
                                isDark
                                    ? 'border-white/10 bg-black/30 text-white placeholder:text-gray-400'
                                    : 'border-slate-300 bg-white text-slate-800 placeholder:text-slate-400'
                            }`}
                        />

                        <div className="mt-4 flex flex-wrap gap-3">
                            <PrimaryButton onClick={runPrediction} disabled={loading} className="px-6 py-3 disabled:opacity-60">
                                {loading ? <LoaderCircleIcon className="size-4 animate-spin" /> : <RadarIcon className="size-4" />}
                                {loading ? 'Analyzing...' : 'Analyze Now'}
                            </PrimaryButton>
                            <GhostButton
                                onClick={() => {
                                    setText('Authorities announce miracle fuel made from ocean water with no evidence provided.');
                                    toast.success('Sample text loaded.');
                                }}
                            >
                                Use sample text
                            </GhostButton>
                        </div>

                        <p className={`mt-4 text-xs ${isDark ? 'text-gray-400' : 'text-slate-500'}`}>
                            Endpoint: {API_ENDPOINT}
                        </p>
                    </motion.div>

                    <motion.div
                        initial={{ y: 80, opacity: 0 }}
                        whileInView={{ y: 0, opacity: 1 }}
                        viewport={{ once: true }}
                        transition={{ type: 'spring', stiffness: 250, damping: 70, mass: 1, delay: 0.1 }}
                        className={`rounded-2xl border p-6 ${
                            isDark ? 'border-white/10 bg-slate-900/60' : 'border-slate-200 bg-white/90 shadow-xl shadow-slate-900/5'
                        }`}
                    >
                        <p className={`text-sm font-medium ${isDark ? 'text-cyan-300' : 'text-cyan-700'}`}>Model result preview</p>

                        {!result && (
                            <div className={`mt-5 rounded-xl border border-dashed p-5 text-sm ${
                                isDark
                                    ? 'border-white/15 bg-black/20 text-gray-300'
                                    : 'border-slate-300 bg-slate-50 text-slate-600'
                            }`}>
                                Submit text to view a model verdict, confidence score and explanation.
                            </div>
                        )}

                        {result && (
                            <div className="mt-5 space-y-4">
                                <div className={`flex items-center justify-between rounded-xl border p-4 ${
                                    isDark ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'
                                }`}>
                                    <div className="flex items-center gap-2">
                                        {result.verdict === 'FAKE' ? (
                                            <AlertTriangleIcon className="size-5 text-amber-300" />
                                        ) : (
                                            <CheckCircle2Icon className="size-5 text-emerald-300" />
                                        )}
                                        <p className={`text-sm ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>Verdict</p>
                                    </div>
                                    <span className={`text-xs px-3 py-1 rounded-full border ${result.verdict === 'FAKE'
                                        ? 'text-amber-200 border-amber-300/40 bg-amber-700/20'
                                        : result.verdict === 'REAL'
                                            ? 'text-emerald-200 border-emerald-300/40 bg-emerald-700/20'
                                            : isDark
                                                ? 'text-gray-200 border-white/30 bg-white/10'
                                                : 'text-slate-600 border-slate-300 bg-slate-100'
                                        }`}>
                                        {result.verdict}
                                    </span>
                                </div>

                                <div className={`rounded-xl border p-4 ${isDark ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
                                    <p className={`text-sm ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>Confidence</p>
                                    <p className={`mt-1 text-2xl font-semibold ${isDark ? 'text-white' : 'text-slate-900'}`}>{confidenceLabel}</p>
                                </div>

                                <div className={`rounded-xl border p-4 ${isDark ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
                                    <p className={`text-sm ${isDark ? 'text-gray-300' : 'text-slate-600'}`}>Explanation</p>
                                    <p className={`mt-2 text-sm leading-relaxed ${isDark ? 'text-gray-200' : 'text-slate-700'}`}>{result.explanation}</p>
                                </div>
                            </div>
                        )}
                    </motion.div>
                </div>
            </div>
        </section>
    );
}
